Fix undeclared identifier 'haveName' in project_serializer.cpp - Removed orphaned assignment 'haveName=true;' on line 91 - Variable declaration was previously removed but assignment remained - Fixes Linux build failure at step [52/145] - Also fixes Windows build error C2065